/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface AppBouncingBall {
    }
    interface AppCounter {
    }
    interface AppMap {
        "fromTo": boolean;
        "isColorize": boolean;
        "isDark": boolean;
        "isMap": boolean;
        "isTooltipEnable": boolean;
        "onlyTram": boolean;
    }
    interface MyComponent {
        /**
          * The first name
         */
        "first": string;
        /**
          * The last name
         */
        "last": string;
        /**
          * The middle name
         */
        "middle": string;
    }
}
declare global {
    interface HTMLAppBouncingBallElement extends Components.AppBouncingBall, HTMLStencilElement {
    }
    var HTMLAppBouncingBallElement: {
        prototype: HTMLAppBouncingBallElement;
        new (): HTMLAppBouncingBallElement;
    };
    interface HTMLAppCounterElement extends Components.AppCounter, HTMLStencilElement {
    }
    var HTMLAppCounterElement: {
        prototype: HTMLAppCounterElement;
        new (): HTMLAppCounterElement;
    };
    interface HTMLAppMapElement extends Components.AppMap, HTMLStencilElement {
    }
    var HTMLAppMapElement: {
        prototype: HTMLAppMapElement;
        new (): HTMLAppMapElement;
    };
    interface HTMLMyComponentElement extends Components.MyComponent, HTMLStencilElement {
    }
    var HTMLMyComponentElement: {
        prototype: HTMLMyComponentElement;
        new (): HTMLMyComponentElement;
    };
    interface HTMLElementTagNameMap {
        "app-bouncing-ball": HTMLAppBouncingBallElement;
        "app-counter": HTMLAppCounterElement;
        "app-map": HTMLAppMapElement;
        "my-component": HTMLMyComponentElement;
    }
}
declare namespace LocalJSX {
    interface AppBouncingBall {
    }
    interface AppCounter {
    }
    interface AppMap {
        "fromTo"?: boolean;
        "isColorize"?: boolean;
        "isDark"?: boolean;
        "isMap"?: boolean;
        "isTooltipEnable"?: boolean;
        "onlyTram"?: boolean;
    }
    interface MyComponent {
        /**
          * The first name
         */
        "first"?: string;
        /**
          * The last name
         */
        "last"?: string;
        /**
          * The middle name
         */
        "middle"?: string;
    }
    interface IntrinsicElements {
        "app-bouncing-ball": AppBouncingBall;
        "app-counter": AppCounter;
        "app-map": AppMap;
        "my-component": MyComponent;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "app-bouncing-ball": LocalJSX.AppBouncingBall & JSXBase.HTMLAttributes<HTMLAppBouncingBallElement>;
            "app-counter": LocalJSX.AppCounter & JSXBase.HTMLAttributes<HTMLAppCounterElement>;
            "app-map": LocalJSX.AppMap & JSXBase.HTMLAttributes<HTMLAppMapElement>;
            "my-component": LocalJSX.MyComponent & JSXBase.HTMLAttributes<HTMLMyComponentElement>;
        }
    }
}
